version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: onboarding_development
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_DATABASE: onboarding_development

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: /bin/sh -c "npm run dev"

volumes:
  db-data: