FROM ruby:3.2

# 追加
ENV RUBYOPT="-rlogger"

# RUN apt-get update -qq && apt-get install -y \
#   nodejs \
#   default-mysql-client \
#   libmysqlclient-dev

RUN apt-get update -qq && apt-get install -y \
  nodejs \
  default-mysql-client \
  default-libmysqlclient-dev \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# COPY Gemfile Gemfile.lock ./
# RUN bundle install

# 【修正】まず Gemfile のみコピーして bundle install を実行（Gemfile.lock が無くても動く）
COPY Gemfile /app/Gemfile
RUN bundle install --jobs=4 --retry=3

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]